### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by erdeme36** [Shreyz-max/Video-Captioning#9]
Traceback (most recent call last):
  File "predict_realtime.py", line 214, in <module>
    video_caption, file = video_to_text.test()
  File "predict_realtime.py", line 161, in test
    sentence_predicted = self.greedy_search(X_test.reshape((-1, 80, 4096)))
  File "predict_realtime.py", line 45, in greedy_search
    output_tokens, h, c = self.inf_decoder_model.predict([target_seq] + states_value)
AttributeError: 'NoneType' object has no attribute 'predict'

This is the error that I encounter with

**Comment by A-MMz** [comment]
I have the same problem

**Comment by adeljalalyousif** [comment]
in **config.py** add the following line:
time_steps_decoder = None

**Comment by tranhuynhkyanh** [comment]
> in **config.py** add the following line: time_steps_decoder = None

it not working :(

**Comment by Shreyz-max** [comment]
I am so sorry guys I have been busy for sometime now. I will try and fix it this weekend.

**Comment by adeljalalyousif** [comment]
In File **"predict_realtime.py"**  delete the following: 
line 27     self.inf_decoder_model = None
This work with me

**Comment by 42Viva** [comment]
> In File **"predict_realtime.py"** delete the following: line 27 self.inf_decoder_model = None This work with me

It works, thx 4 ur note.

**Comment by luoshuiyang** [comment]
> In File **"predict_realtime.py"** delete the following: line 27 self.inf_decoder_model = None This work with me

it works for me! thank you.
